packages:
  - "packages/*"
  - "apps/*"

catalog:
  prettier: ^3.5.3
  typescript: ^5.8.2
  tsx: ^4.16.2
  dotenv-cli: ^7.4.2
  react: ^19.0.0
  react-dom: ^19.0.0
  next: ^15.2.3
  "@prisma/client": ^6.8.2
  prisma: ^6.8.2
  zod: "^3.25.42"
  tailwindcss: ^4.0.15
  "@tailwindcss/postcss": ^4.0.15
  next-auth: ^5.0.0-beta.25
  "@auth/core": ^0.39.1
  "@auth/prisma-adapter": ^2.9.1
